apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
    nodePort: 30001  # Access via http://localhost:30001
